# Generated by Django 5.2.5 on 2025-08-31 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_blog_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='read',
            field=models.IntegerField(default=0),
        ),
    ]
