# Generated by Django 5.2.5 on 2025-09-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='thumbnail/user.png', upload_to='thumbnail/'),
        ),
    ]
