# Generated by Django 5.2.5 on 2025-09-02 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='image',
        ),
    ]
