# Generated by Django 5.2.5 on 2025-09-02 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='thumbnail/user.png', upload_to='thumbnail/'),
        ),
    ]
